add unit tests for PatientService class
irinaenescu2002/Testarea-Sistemelor-Software-2024 pull request #4
Opened 2024-03-30 20:13 UTC by irinaenescu2002

2024-03-31 06:15 UTC, Qmpzlawasd requested changes

2024-03-31 06:15 UTC, Qmpzlawasd commented on backend/src/test/java/ro/boa/clinic/unit/PatientServiceTest.java
> +    private PatientRepository patientRepository;
add some newlines here

2024-03-31 13:43 UTC, irinaenescu2002 commented on backend/src/test/java/ro/boa/clinic/unit/PatientServiceTest.java
> +    private PatientRepository patientRepository;
![image](https://github.com/irinaenescu2002/Testarea-Sistemelor-Software-2024/assets/93870739/adc95fde-eff0-4bb2-b8f8-91d31e4654c1)

2024-04-01 11:32 UTC, irinaenescu2002 commented on backend/src/test/java/ro/boa/clinic/unit/PatientServiceTest.java
> +    private PatientRepository patientRepository;
done

2024-04-01 11:36 UTC, merged